function [X, out] = Un_Solver(A, shape, opts)
    % This function solves
    %    min     V(x)' * A * V(x)
    %    s.t.    X is unitary matrix
    % where X is the matrix of r * I, generated by the left unfolding of a
    % 3 order tensor r_{i-1} * Ii * ri
 
    x = eye(shape(1) * shape(2), shape(3));
    [X, out]= OptStiefelGBB(x, @ProblemUnitary, opts, A);
    X = reshape(X, shape);
end

function [f, g] = ProblemUnitary(x, A)
    % x is a matrix (R_{i-1}I_i) * R_i
    % A is a matrix (R_{i-1}I_i) * (R_{i-1}I_i)
    f = trace(x' * A * x);
    g = 2 * A' * x;
end